PostgreSQL:
  restart: always
  image: sameersbn/postgresql:9.4-18
  net: "host"
  environment:
    - DEBUG=false
    - PG_TRUST_LOCALNET=true
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
