PostgreSQL:
  restart: always
  image: sameersbn/postgresql:9.4-18
  net: "host"
  environment:
    - PG_TRUST_LOCALNET=true
    - DB_USER=$USER
    - DB_PASS=doesnotmatter
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
